### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by zhoudreames** [google/deepconsensus#1]
there are error show you blow when using code `pip install deepconsensus==0.1.0`
![image](https://user-images.githubusercontent.com/54714639/131625131-9a8b0635-c7f2-4379-bae6-1dbb068d0a96.png)

**Comment by zhoudreames** [comment]
![image](https://user-images.githubusercontent.com/54714639/131625225-264ccb7a-6336-4384-a214-1fc6ee8a62ea.png)

**Comment by armintoepfer** [comment]
Hey there, looks like it requires a specific python version
From: https://pypi.org/project/deepconsensus/

> Requires: Python >=3.6, <3.7

**Comment by zhoudreames** [comment]
> Hey there, looks like it requires a specific python version
> From: https://pypi.org/project/deepconsensus/
> 
> > Requires: Python >=3.6, <3.7

thanks~
