### ISSUE TITLE
deepconsensus.scripts.run_deepconsensus  errors

### ISSUE THREAD

**Issue by zhoudreames** [google/deepconsensus#13]
i got some errors show in blow when i run  python3 -m   deepconsensus.scripts.run_deepconsensus  --input_subreads_aligned=P05TYD21354128-1_r64114_20210126_052631_1_A02.subreads_to_ccs.bam   --input_subreads_unaligned=DRC_chr3_20Mb_rmTail.P05TYD21354128-1_r64114_20210126_052631_1_A02.bam   --input_ccs_fasta=P05TYD21354128-1_r64114_20210126_052631_1_A02.ccs.fasta   --output_directory=1.tmp   --checkpoint=01.DeepConsusModel
![image](https://user-images.githubusercontent.com/54714639/141939379-750d377d-acc7-4739-8cbd-cbb3e15ae25c.png)
 i dont know how to solve it ,could you help me ?thanks~

**Comment by danielecook** [comment]
@zhoudreames can you try installing bzip2 in the conda env you are using?

Something like this...

`conda install -c conda-forge -c bioconda bzip2`

**Comment by pichuan** [comment]
Hi @zhoudreames , we've made a release in January that cleaned up a code quite a bit.
And it now includes a Docker solution as well. If you're still encountering issues, please feel free to report again!
