### ISSUE TITLE
Docker or Singularity

### ISSUE THREAD

**Issue by AMMMachado** [google/deepconsensus#15]
Hi,

First of all thank you for this amazing program.
I'm working in a cluster with the centos7. I tried to install the software several times, always with errors in the pip/Python distributions. Could you make available some docker and/or singularity for the deep consensus? 
Best Regards
Andre

**Comment by MariaNattestad** [comment]
Hi Andre,

Yes, we are currently working on a version of DeepConsensus which will be easier to install with pip, and this new version will also include a docker image that should work with singularity as well.

Maria

**Comment by gevro** [comment]
Great to hear! Is there an estimate for when this might be available?

**Comment by AMMMachado** [comment]
Thank you @MariaNattestad . Currently, we are performing several genome assemblies, and we intend to include deepconsensus in our PcabioHifi pipeline. Do you have some time estimation for the next stable release?

André

**Comment by MariaNattestad** [comment]
We're hoping to have a release ready by the end of January, assuming all goes well :)

**Comment by MariaNattestad** [comment]
The release is now available! https://github.com/google/deepconsensus/releases/tag/v0.2.0
