### ISSUE TITLE
pip install deepconsensus==0.1.0 fails...

### ISSUE THREAD

**Issue by sjin09** [google/deepconsensus#2]
Hello,

I don't have sudo privileges on my server and I would love to try using deepconsensus. I have attempting installing deepconsensus through the recommended method.

The following commands: 

```bash
pip install deepconsensus==0.1.0
pip install deepconsensus
```

returns

```
ERROR: Could not find a version that satisfies the requirement deepconsensus (from versions: none)
ERROR: No matching distribution found for deepconsensu
```

The server details are as follows:
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Regards,
Sangjin

**Comment by armintoepfer** [comment]
Please see https://github.com/google/deepconsensus/issues/1

**Comment by sjin09** [comment]
```python
conda create -n py3 python=3.6
source activate py3
pip install deepconsensus==0.1.0
```
