### ISSUE TITLE
DeepConsensus model is not accessed from China

### ISSUE THREAD

**Issue by zhangrengang** [google/deepconsensus#22]
Hi, I am a user from China and I can not access the model via gsutil. Would you please also place the model in github? The model should be small files?

**Comment by pichuan** [comment]
@zhangrengang Can you try if you can wget these files:

https://storage.googleapis.com/brain-genomics-public/research/deepconsensus/models/v0.2/params.json
https://storage.googleapis.com/brain-genomics-public/research/deepconsensus/models/v0.2/checkpoint-50.index
https://storage.googleapis.com/brain-genomics-public/research/deepconsensus/models/v0.2/checkpoint-50.data-00000-of-00001

**Comment by zhangrengang** [comment]
Thanks, I can download them.
