### ISSUE TITLE
Merging aligned fastq output with original ccs BAM

### ISSUE THREAD

**Issue by gevro** [google/deepconsensus#39]
Is there a recommended approach / best practices for merging aligned deepconsensus fastq output with the original ccs BAM file, so that aligned deepconsensus reads are re-associated with the tags from the original ccs BAM (eg, ec, np, sn, zm, etc tags)?

(This issue could also be fixed by making deepconsensus output as BAM instead of fastq. )

**Comment by danielecook** [comment]
One simple approach here would be to iterate through the FASTQ and the original BAM using pysam.

You can substitute the sequence from the FASTQ, but the PW and IPD tags will not necessarily align, because DeepConsensus can result in sequence lengths that differ from the PW/IPD lengths.

**Comment by gevro** [comment]
Ok thanks. I may try GATK MergeBamAlignment too.
