### ISSUE TITLE
Strand of Fastq output

### ISSUE THREAD

**Issue by gevro** [google/deepconsensus#41]
Hi,
Deepconsensus takes as one of its input a CCS BAM file.

When the CCS BAM file is already aligned to the genome, does deepconsensus reverse complement the sequence for reads that align to the reverse strand of the genome, such that the output FASTQ of that molecule will be in the original unaligned orientation?

From what I can see, I think this is not happening, which is ok, but just wanted to confirm. Because this means that inputting an unaligned CCS BAM versus an aligned CCS BAM will produce a different FASTQ output, whereby reads that aligned to the reverse strand will have the reverse orientation in the deepconsensus FASTQ output.

**Comment by danielecook** [comment]
The CCS BAM file is expected to be unaligned. I don't think we have looked at using aligned CCS BAMs before. Presumably, the subread_to_ccs.bam would also be derived from an aligned ccs.bam, in which case it might work and reverse-complement the sequences where appropriate, but I would advise performing alignment to a reference after DeepConsensus processing has taken place.

**Comment by gevro** [comment]
Ok thanks. I am now using picard RevertSam to transform the aligned CCS BAM to unaligned CCS BAM.
