### ISSUE TITLE
actc and kinetic data orientation

### ISSUE THREAD

**Issue by gevro** [google/deepconsensus#43]
Hi, actc is used to align subreads to ccs, but does actc reverse the orientation of kinetic (ip/pw) data in the BAM file it outputs? Or does Deepconsensus do this? I'm assuming either actc or Deepconsensus would have to do this to ensure that the kinetic data is in the correct orientation with the subreadstoccs alignment.

Thanks.

**Comment by armintoepfer** [comment]
Looking at two input subreads and their alignments or reading the PacBio BAM spec that you are well aware of, you'll figure out no aligner will change the orientation of tags.

**Comment by pichuan** [comment]
Hi @gevro , I'm closing this issue. If you have more questions, please feel free to open another issue or reopen. Thank you!
