### ISSUE TITLE
deepconsensus on metagenomic data

### ISSUE THREAD

**Issue by ay-amityadav** [google/deepconsensus#44]
Hi,

Is it ok to run deepconsensus on HiFi metagenomic data? I can see that it has been tested on human genomic data.

Many thanks

**Comment by AndrewCarroll** [comment]
Hi @ay-amityadav,

Thank you for your question. DeepConsensus should work for metagenomic data. We've tested DeepConsensus on E.coli and several plant species. For E.coli we see higher accuracy as measured against the known sequence of the reference strain. For plant species, we see improvements to assembly contiguity and correctness.

As a result of those investigations, we believe DeepConsensus should work well for metagenomic samples as well.

**Comment by ay-amityadav** [comment]
Thank you very much!
