### ISSUE TITLE
no subreads available

### ISSUE THREAD

**Issue by michaelabrouk** [google/deepconsensus#45]
Hi, 

I am working with sequencing output coming from Sequel IIe meaning that I only have the ccs.bam files available and not the subreads.bam.
Is DeepConsensus can work without the alignment of subreads to ccs using actc in the preliminary step?

Thanks

**Comment by armintoepfer** [comment]
DeepConsensus requires subreads, which are not available when using Sequel IIe HiFi output.

**Comment by michaelabrouk** [comment]
Thank you for your answer.
