### ISSUE TITLE
python 3.9

### ISSUE THREAD

**Issue by hildebra** [google/deepconsensus#58]
Just a comment on the installer, for me python 3.10 won't work with the dependencies, but this can be easily fixed using the command:

micromamba create -n PacBio -y -c bioconda -c anaconda pbbam pbccs actc pip python=3.9; micromamba activate PacBio; pip install deepconsensus[cpu]==1.1.0

(and respective for conda/mamba) to install deepconsensus locally
hth other users, Falk

**Comment by pichuan** [comment]
Thanks @hildebra . It seems like you were able to resolve the issue. Thanks for sharing! I'll close this issue.

**Comment by AlcaArctica** [comment]
Thank you @hildebra . This helped me. I managed to install the most recent deepconsensus with:
```
mamba create -n deepconsensus -y -c bioconda -c anaconda pbbam pbccs actc pip python=3.9
mamba activate deepconsensus
pip install --upgrade pip setuptools wheel
pip install deepconsensus[cpu]==1.2.0
```
