### ISSUE TITLE
QV for each ccs reads

### ISSUE THREAD

**Issue by Wenfei-Xian** [google/deepconsensus#61]
Hi,
      Many thanks for the amazing tool !
      I just wonder it is possible to output the QV for each deepconsensu ccs reads?
      Here is the pbccs output : @m64079_220112_082130/103153878/ccs np=19 rq=0.999962, it contains the np and rq information for each reads.
      However, for deepconsensus output: @m64079_220112_082130/103153878/ccs, no other information contained, except for reads name.
      I want to obtain the Q20 reads , Q30 reads and Q40 reads seperately. Can you point me how to deal with instead of running deepconsensus three times. 
Best,
Wenfei

**Comment by kishwarshafin** [comment]
Hello @Wenfei-Xian ,

Really sorry for such a late reply. We had a long chat about what exactly to do to support this. Finally, we have decided to provide a command line option to filter reads at any given Q-point.

With the latest DeepConsensus release of 1.2.0 you can run:
```bash
deepconsensus filter_reads --help

Filter reads based on the base qualities.
Flags:
    --input_seq            Path to input fastq or bam file.
    --output_fastq         Path to output fastq file.
    --quality_threshold    A quality threshold value applied per read.  Reads with read quality below this will be filtered out.
```
And see the option to filter your fastq at any given q-value. Please give it a try.

**Comment by Wenfei-Xian** [comment]
Many thanks !!!!!
