### ISSUE TITLE
Separate subreads for mixed samples?

### ISSUE THREAD

**Issue by icemduru** [google/deepconsensus#68]
I have one SMRT Cell that contains two different samples with barcode information. Should I first separate my subreads based on the barcode info, or should I run DeepConsensus with the mixed subreads and then separate the reads with the barcode info from the HiFi output?

**Comment by pgrosu** [comment]
Hi Ilhan,

Yes you should split them first with `lima`, and here are a couple of reference posts regarding this:

[Issue 32](https://github.com/google/deepconsensus/issues/32)

https://github.com/PacificBiosciences/pbbioconda/issues/523

Hope it helps,
Paul

**Comment by icemduru** [comment]
thanks ! and sorry for duplicate

**Comment by icemduru** [comment]
closed
