### ISSUE TITLE
pbccs parameters

### ISSUE THREAD

**Issue by AllanSSX** [google/deepconsensus#7]
Hello,

In the online methods, you indicate that you didn't apply any filtering based on read quality for the CCS reads, and reads of qualities were included in the training dataset from pbccs output. Can you indicate the exact command line you used to generate ccs file?

Regards,
Alex

**Comment by armintoepfer** [comment]
Hey Alex,

`--all` is sufficient.

Armin

**Comment by danielecook** [comment]
Yep - we used `--all` with `ccs`.
